### ISSUE TITLE
msmbuilder API has changed?

### ISSUE THREAD

**Issue by daveminh** [choderalab/ensembler#89]
I get this error:

Constructing a trajectory containing all valid models...
Conducting RMSD-based clustering...
Traceback (most recent call last):
  File "/share/apps/anaconda/2/bin/ensembler", line 6, in <module>
    sys.exit(ensembler.cli.main())
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/cli.py", line 40, in main
    command.dispatch(args)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/cli_commands/quickmodel.py", line 106, in dispatch
    QuickModel(targetid=args['--targetid'], templateids=templateids, target_uniprot_entry_name=args['--target_uniprot_entry_name'], uniprot_domain_regex=args['--uniprot_domain_regex'], pdbids=pdbids, chainids=chainids_dict, template_uniprot_query=args['--template_uniprot_query'], template_seqid_cutoff=template_seqid_cutoff, loopmodel=not args['--no-loopmodel'], package_for_fah=args['--package_for_fah'], nfahclones=nfahclones, structure_dirs=structure_paths)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/tools/quick_model.py", line 95, in __init__
    self._model(self.targetid, self.templateids, loopmodel=self.loopmodel, package_for_fah=self.package_for_fah, nfahclones=self.nfahclones)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/tools/quick_model.py", line 141, in _model
    ensembler.modeling.cluster_models(process_only_these_targets=targetid)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/utils.py", line 29, in wrapper
    fn(*args, **kwargs)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/utils.py", line 37, in print_done
    fn(*args, **kwargs)
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/modeling.py", line 832, in cluster_models
    valid_templateids, traj, atom_indices=CAatoms, cutoff=cutoff
  File "/share/apps/anaconda/2/lib/python2.7/site-packages/ensembler/modeling.py", line 896, in models_regular_spatial_clustering
    cluster = msmbuilder.cluster.RegularSpatial(cutoff, metric='rmsd')

msmbuilder.cluster.RegularSpatial does not appear to exist. I have the msmbuilder from conda.

[dminh@ccb ensembler]$ conda install msmbuilder
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /share/apps/anaconda/2:
#
msmbuilder                3.6.1               np111py27_0    omnia

This shows that it doesn't exist:

Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import msmbuilder

In [2]: import msmbuilder.
msmbuilder.Citation      msmbuilder.cfep          msmbuilder.msm_analysis  msmbuilder.tpt
msmbuilder.License       msmbuilder.clustering    msmbuilder.plot_graph    msmbuilder.utils
msmbuilder.MSMLib        msmbuilder.drift         msmbuilder.project       msmbuilder.version
msmbuilder.SCRE          msmbuilder.fahproject    msmbuilder.reduce        
msmbuilder.arglib        msmbuilder.lumping       msmbuilder.scripts       
msmbuilder.assigning     msmbuilder.metrics       msmbuilder.testing       

In [2]: import msmbuilder.clustering

In [3]: import msmbuilder.clustering.
msmbuilder.clustering.BaseFlatClusterer              msmbuilder.clustering.logging
msmbuilder.clustering.Clarans                        msmbuilder.clustering.md
msmbuilder.clustering.Hierarchical                   msmbuilder.clustering.metrics
msmbuilder.clustering.HybridKMedoids                 msmbuilder.clustering.np
msmbuilder.clustering.KCenters                       msmbuilder.clustering.p_norm
msmbuilder.clustering.PY2                            msmbuilder.clustering.print_function
msmbuilder.clustering.Pool                           msmbuilder.clustering.random
msmbuilder.clustering.SubsampledClarans              msmbuilder.clustering.scipy
msmbuilder.clustering.absolute_import                msmbuilder.clustering.split
msmbuilder.clustering.concatenate_prep_trajectories  msmbuilder.clustering.stochastic_subsample
msmbuilder.clustering.concatenate_trajectories       msmbuilder.clustering.sys
msmbuilder.clustering.deterministic_subsample        msmbuilder.clustering.types
msmbuilder.clustering.division                       msmbuilder.clustering.unconcatenate_trajectory
msmbuilder.clustering.fastcluster                    msmbuilder.clustering.uneven_zip
msmbuilder.clustering.io                             msmbuilder.clustering.xrange
msmbuilder.clustering.logger

**Comment by jchodera** [comment]
Yeah, the `msmbuilder` API has changed, and we're not pinning to a specific version at the moment. 

I would suggest you force `conda` to install the version we used for the paper, which was probably 3.3.1:
```bash
conda install --yes msmbuilder==3.3.1
```
